//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSteamLauncher {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPSteamLauncher.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Last used 的本地化字符串。
        /// </summary>
        internal static string AppLastUsed {
            get {
                return ResourceManager.GetString("AppLastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage time in last 2 weeks 的本地化字符串。
        /// </summary>
        internal static string AppUsetime2wks {
            get {
                return ResourceManager.GetString("AppUsetime2wks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage time 的本地化字符串。
        /// </summary>
        internal static string AppUsetimeTotal {
            get {
                return ResourceManager.GetString("AppUsetimeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Game 的本地化字符串。
        /// </summary>
        internal static string GameDescription {
            get {
                return ResourceManager.GetString("GameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        internal static string GameId {
            get {
                return ResourceManager.GetString("GameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Played 的本地化字符串。
        /// </summary>
        internal static string GameLastPlayed {
            get {
                return ResourceManager.GetString("GameLastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play time in last 2 weeks 的本地化字符串。
        /// </summary>
        internal static string Gametime2wks {
            get {
                return ResourceManager.GetString("Gametime2wks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play time 的本地化字符串。
        /// </summary>
        internal static string GametimeTotal {
            get {
                return ResourceManager.GetString("GametimeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application 的本地化字符串。
        /// </summary>
        internal static string GameTypeApp {
            get {
                return ResourceManager.GetString("GameTypeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 的本地化字符串。
        /// </summary>
        internal static string GameTypeGame {
            get {
                return ResourceManager.GetString("GameTypeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool 的本地化字符串。
        /// </summary>
        internal static string GameTypeTool {
            get {
                return ResourceManager.GetString("GameTypeTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Launcher can&apos;t be initialized 的本地化字符串。
        /// </summary>
        internal static string InitializationFailedTitle {
            get {
                return ResourceManager.GetString("InitializationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game properties 的本地化字符串。
        /// </summary>
        internal static string OpenGamePropsTitle {
            get {
                return ResourceManager.GetString("OpenGamePropsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch your steam games. 的本地化字符串。
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Launcher 的本地化字符串。
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch 的本地化字符串。
        /// </summary>
        internal static string StartGameTitle {
            get {
                return ResourceManager.GetString("StartGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try re-install Steam by official installer. 的本地化字符串。
        /// </summary>
        internal static string SteamNotFoundDescription {
            get {
                return ResourceManager.GetString("SteamNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find Steam 的本地化字符串。
        /// </summary>
        internal static string SteamNotFoundTitle {
            get {
                return ResourceManager.GetString("SteamNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} days 的本地化字符串。
        /// </summary>
        internal static string TimeAbsDay {
            get {
                return ResourceManager.GetString("TimeAbsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} hours 的本地化字符串。
        /// </summary>
        internal static string TimeAbsHour {
            get {
                return ResourceManager.GetString("TimeAbsHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} minutes 的本地化字符串。
        /// </summary>
        internal static string TimeAbsMin {
            get {
                return ResourceManager.GetString("TimeAbsMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never opened 的本地化字符串。
        /// </summary>
        internal static string TimeAbsNever {
            get {
                return ResourceManager.GetString("TimeAbsNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} seconds 的本地化字符串。
        /// </summary>
        internal static string TimeAbsSec {
            get {
                return ResourceManager.GetString("TimeAbsSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} days ago 的本地化字符串。
        /// </summary>
        internal static string TimeRelativeDay {
            get {
                return ResourceManager.GetString("TimeRelativeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} hours ago 的本地化字符串。
        /// </summary>
        internal static string TimeRelativeHour {
            get {
                return ResourceManager.GetString("TimeRelativeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Just now 的本地化字符串。
        /// </summary>
        internal static string TimeRelativeJustNow {
            get {
                return ResourceManager.GetString("TimeRelativeJustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} minutes ago 的本地化字符串。
        /// </summary>
        internal static string TimeRelativeMin {
            get {
                return ResourceManager.GetString("TimeRelativeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} seconds ago 的本地化字符串。
        /// </summary>
        internal static string TimeRelativeSec {
            get {
                return ResourceManager.GetString("TimeRelativeSec", resourceCulture);
            }
        }
    }
}
